package Clases;
// Generated Oct 2, 2016 10:39:18 PM by Hibernate Tools 4.3.1



/**
 * Llamado generated by hbm2java
 */
public class Llamado  implements java.io.Serializable {


     private int id;
     private int idMesa;
     private int idMozo;
     private String fechaHora;
     private String estado;

    public Llamado() {
    }

    public Llamado(int id, int idMesa, int idMozo, String fechaHora, String estado) {
       this.id = id;
       this.idMesa = idMesa;
       this.idMozo = idMozo;
       this.fechaHora = fechaHora;
       this.estado = estado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdMesa() {
        return this.idMesa;
    }
    
    public void setIdMesa(int idMesa) {
        this.idMesa = idMesa;
    }
    public int getIdMozo() {
        return this.idMozo;
    }
    
    public void setIdMozo(int idMozo) {
        this.idMozo = idMozo;
    }
    public String getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(String fechaHora) {
        this.fechaHora = fechaHora;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


