package Clases;
// Generated Oct 2, 2016 10:39:18 PM by Hibernate Tools 4.3.1



/**
 * Mesa generated by hbm2java
 */
public class Mesa  implements java.io.Serializable {


     private int id;
     private String numero;
     private int idMozo;
     private boolean activo;

    public Mesa() {
    }

    public Mesa(int id, String numero, int idMozo, boolean activo) {
       this.id = id;
       this.numero = numero;
       this.idMozo = idMozo;
       this.activo = activo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public int getIdMozo() {
        return this.idMozo;
    }
    
    public void setIdMozo(int idMozo) {
        this.idMozo = idMozo;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }




}


