package Clases;
// Generated Oct 2, 2016 10:39:18 PM by Hibernate Tools 4.3.1



/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private int id;
     private int idMozo;
     private int idMesa;
     private int idPlato;
     private String fechaHora;
     private String estadoPlato;
     private String estado;

    public Pedido() {
    }

    public Pedido(int id, int idMozo, int idMesa, int idPlato, String fechaHora, String estadoPlato, String estado) {
       this.id = id;
       this.idMozo = idMozo;
       this.idMesa = idMesa;
       this.idPlato = idPlato;
       this.fechaHora = fechaHora;
       this.estadoPlato = estadoPlato;
       this.estado = estado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getIdMozo() {
        return this.idMozo;
    }
    
    public void setIdMozo(int idMozo) {
        this.idMozo = idMozo;
    }
    public int getIdMesa() {
        return this.idMesa;
    }
    
    public void setIdMesa(int idMesa) {
        this.idMesa = idMesa;
    }
    public int getIdPlato() {
        return this.idPlato;
    }
    
    public void setIdPlato(int idPlato) {
        this.idPlato = idPlato;
    }
    public String getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(String fechaHora) {
        this.fechaHora = fechaHora;
    }
    public String getEstadoPlato() {
        return this.estadoPlato;
    }
    
    public void setEstadoPlato(String estadoPlato) {
        this.estadoPlato = estadoPlato;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


