package Clases;
// Generated Oct 2, 2016 10:39:18 PM by Hibernate Tools 4.3.1



/**
 * Plato generated by hbm2java
 */
public class Plato  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private String foto;
     private float precio;
     private boolean activo;

    public Plato() {
    }

    public Plato(int id, String nombre, String descripcion, String foto, float precio, boolean activo) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.foto = foto;
       this.precio = precio;
       this.activo = activo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }




}


